### ISSUE TITLE
这个库支持别的语言吗？

### ISSUE THREAD

**Issue by vic233333** [AlexandaJerry/whisper-vits-japanese#10]
如果我的数据集里面有来自其它语言，比如中英韩的语音该项目能够正常工作吗？whisper和VITS是支持多语言的，不知道这个项目能不能多语言。

**Comment by AlexandaJerry** [comment]
> 如果我的数据集里面有来自其它语言，比如中英韩的语音该项目能够正常工作吗？whisper和VITS是支持多语言的，不知道这个项目能不能多语言。

很明显是非常可以，甚至简单到不想改项目。只需要自己放进特定语言的cleaner，然后whisper指定这个语言就行（文本处理的时候拿新cleaner处理）

**Comment by AlexandaJerry** [comment]
推荐可以看下cjancjang的仓库自行学习

**Comment by vic233333** [comment]
> 推荐可以看下cjancjang的仓库自行学习

感谢！
